@ReturnValuesAreNonnullByDefault
@FieldsAreNonnullByDefault
@ParametersAreNonnullByDefault
package corewar.pit;

import corewar.shared.FieldsAreNonnullByDefault;
import corewar.shared.ReturnValuesAreNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;